ballerina-platform/ballerina-library

.github/workflows/publish_snapshots.yml, .github/workflows/release_pipeline.yml
=> Fix incorrect paths in release and publish workflows

release/resources/stdlib_modules.json, release/src/release/utils/constants.bal
=> Enable releases for slp5

release/resources/stdlib_modules.json
Added FTP module to Standard Library pipeline.
=> Add FTP module to pipeline

release/src/commons/constants.bal, release/src/publish/publish.bal, release/src/release/release.bal
=> Add retry configs for HTTP client in release pipeline

release/src/publish/publish.bal
=> Update log messages when publishing

release/src/publish/publish.bal
=> Ignore all the build fails and continue the process with warning

release/src/publish/publish.bal
=> Improve logs in publishing workflow

.github/workflows/dependency_graph.yml, release/src/module_dependencies/main.py
Logs to determine the workflow status
=> Logs added to main.py

.github/workflows/dependency_graph.yml
Creating a PR instead of directly committing dependency updates
=> Create PR for dependency updates

release/resources/module_list.json
=> Remove filepath module from build pipeline

release/resources/stdlib_modules.json
=> Disable transaction related module releases

release/resources/stdlib_modules.json
=> Disable all release except jarrays and encoding

release/resources/stdlib_modules.json
=> Disable next release modules

release/resources/stdlib_modules.json
=> Disable already released versions - SLP6

release/resources/stdlib_modules.json
=> Disable FTP

release/resources/stdlib_modules.json
=> Disable unnecessary releases

release/resources/stdlib_modules.json
=> Enable transaction related module releases

release/src/commons/constants.bal
=> Reduce the Sleep Interval and Increase the Max Wait Time in the Build Pipeline

release/resources/module_list.json
$title
Add https://github.com/ballerina-platform/module-ballerinax-stan
Merge after:
=> Add module-ballerinax-stan to module_list.json

release/resources/module_list.json
$subject
To be merged after [#6](https://github.com/ballerina-platform/module-ballerina-graphql/pull/6)
=> Add graphql module to the pipeline

release/resources/module_list.json
=> Add websocket module to pipeline

release/resources/module_list.json
=> Add transaction module to the pipeline

release/src/commons/functions.bal, release/src/publish/publish.bal
=> Improve logs in publishing pipeline

release/resources/module_list.json
=> Fix typo in transaction module name

release/src/publish/publish.bal
=> Fix typo in publish snapshot pipeline

release/src/publish/publish.bal
=> Fix module name not picking from the module list issue

release/resources/module_list.json
=> Add uuid module to pipeline

README.md
=> Add Publish Snapshots Status Badge to the Readme

.github/workflows/dependency_graph.yml, release/src/version_update/main.py
=> Update stdlib Versions in Ballerina Distribution

.github/workflows/module_dependents_build.yml
=> Change the workflow names

release/src/commons/functions.bal
=> Update the workflow name

release/src/commons/functions.bal
=> Fix self cancelling issue

release/src/commons/functions.bal
=> Fix getting the  workflow JSON array

release/resources/module_list.json
=> Update system module name to os

.github/workflows/dependency_graph.yml, .github/workflows/stdlib_dependabot.yml, dependabot/file_update.py, release/src/version_update/main.py
=> Add released version check to update stdlib module versions in Ballerina Distribution

release/resources/module_list.json
=> Add websubhub module

release/src/version_update/main.py
=> Update the module version in Ballerina Distribution when version is not existing

release/resources/module_list.json
=> Remove config module from the pipeline

.github/workflows/update_lang_version.yml
=> Fix workflow failure due to directory missing

.github/workflows/update_lang_version.yml, dependabot/update_lang_version.py
Add sleep between requests to avoid request dropping from GitHub
=> Fix lang update workflow

release/src/version_update/main.py
Change `java.arrays` name in gradle.properties from `stdlibJarraysVersion` to `stdlibJavaArraysVersion`
=> Fix JavaArrays KeyError

dependabot/update_lang_version.py
=> Sync with base branch before committing

dependabot/update_version_data.py
=> Remove fetching version from central

dependabot/update_repositories.py
=> Remove duplicating SNAPSHOT

.github/workflows/stdlib_dependabot.yml
=> Remove commiting condition

dependabot/update_repositories.py
=> Fix dependabot script

dependabot/update_repositories.py
Temporary disable version comparison. Tracked with #961
=> Force commit new version

release/resources/stdlib_modules.json
=> Disable already released module releases

release/resources/stdlib_modules.json
=> Disable the task and L4 modules except TCP

dependabot/update_repositories.py
=> Fix error printing module name

.github/workflows/build_module_dependents.yml, .github/workflows/build_stdlib_modules.yml, .github/workflows/release_pipeline.yml
=> Change ballerina command version

dependabot/update_lang_version.py
=> Fix version update branch already existing error

dependabot/update_lang_version.py
=> Handle merge conflict with base branch

release/resources/module_list.json
=> Update jdbc repo name

dependabot/update_lang_version.py, dependabot/update_repositories.py
=> Update dependency update PR title

dependabot/update_lang_version.py, dependabot/update_repositories.py
=> Make sleep only when a PR is created

dependabot/update_lang_version.py, dependabot/update_repositories.py
=> Change automated PR title

.github/workflows/build_module_dependents.yml, .github/workflows/build_stdlib_modules.yml, .github/workflows/update_dependencies.yml, .github/workflows/update_lang_version.yml
=> Update Workflow Names to Avoid Ambiguity

README.md
=> Update Status Badge links

release/resources/stdlib_modules.json
=> Disable publishing already released modules

release/resources/stdlib_modules.json
Reverts ballerina-platform/ballerina-standard-library#1122
=> Revert "Disable publishing already released modules"

release/src/version_update/update_distribution.py
$subject as it is removed from distribution
=> Remove jdbc special case

release/src/version_update/update_distribution.py
=> Skip SQL modules during version update

release/resources/stdlib_modules.json
=> Skip released stdlibs

release/src/module_dependencies/update_version_data.py
=> Update issue badge to show only bugs

release/src/module_dependencies/update_version_data.py
=> Fix incorrect bugs count in badges

release/src/module_dependencies/update_version_data.py
=> Add GitHub Logo to Bugs Badge

dependabot/update_lang_version.py
=> Stop lang version bump to SNAPSHOT

release/src/module_dependencies/update_version_data.py
=> Remove label from Bugs badge

.github/workflows/stdlib_dependabot.yml
=> Disable version bump PR workflow

release/src/module_dependencies/update_version_data.py
=> Update status dashboard with Timestamped Build badge

release/src/module_dependencies/update_version_data.py
=> Update Build badge

release/src/module_dependencies/update_version_data.py
=> Customise issue label colour

.github/workflows/update_dependencies.yml
=> Increase Dependency Graph Generation Workflow Frequency

release/resources/stdlib_modules.json
=> Mark already released modules in beta1

release/src/commons/records.bal
=> Add version key to module record

release/resources/stdlib_modules.json
=> Mark already released modules

release/resources/module_list.json, release/resources/stdlib_modules.json
Partially fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1593
=> Add MSSQL module to standard library

README.md
=> Remove ballerina dev group reference

release/resources/module_list.json
=> Add protobuf module to stdlibs

resources/scripts/README.md, resources/scripts/build_standard_library.py
This script can be used to clone, build and publish standard libraries incrementally. More information can be found in README.md file.
=> Add Standard Library Build Script

docs/library-development-process.md
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
=> Update security report section

resources/scripts/README.md, resources/scripts/build_standard_library.py
=> Add skip-modules Flag to Standard Library Build Script

.github/workflows/update_dependencies.yml
=> Upgrade github action for Dependency Graph workflow

docs/library-development-process.md
=> Update the development process

docs/library-development-process.md
=> Update the load test section

.github/workflows/update_dependencies.yml
=> Revert git push command changes

.github/workflows/update_dependencies.yml
=> Set username for git push

.github/workflows/update_dependencies.yml
=> Remove checkout action

release/src/module_dependencies/update_version_data.py
=> Change release badge color to green

release/src/module_dependencies/update_version_data.py
=> Fix inccorect badge URL

release/src/module_dependencies/update_version_data.py
=> Fix Incorrect Badge URL

release/src/module_dependencies/update_version_data.py
=> Update badge color

release/src/module_dependencies/update_version_data.py
=> Update the Badge Color to Match with Other Badges

.github/workflows/update_dependencies.yml
=> Fix Workflow Fail on Nothing to Commit and Update the Step Names

.github/workflows/update_dependencies.yml
=> Update Dependency Update Workflow to Run at 8.30 AM/PM on LK Time

release/resources/stdlib_modules.json
=> Disable release

release/src/dependencies/constants.py, release/src/dependencies/utils.py, release/src/dependencies/utils_test.py
**Description**
- Remove open PR column
- Improve following badges
- Remove label part of the build badge
- Remove label part of the Trivy badge
- Remove logo part of the bugs badge
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2519
=> Remove open PR status and improve labels of dashboard

.github/ISSUE_TEMPLATE/type_bug.md, .github/ISSUE_TEMPLATE/type_improvement.md, .github/ISSUE_TEMPLATE/type_new_feature.md, .github/ISSUE_TEMPLATE/type_proposal.md, .github/ISSUE_TEMPLATE/type_task.md
Reverts ballerina-platform/ballerina-standard-library#2790
=> Revert "Update issue templates for updated labels"

release/resources/stdlib_modules.json
$subject related to 2201.1.0 release
=> Exclude releasing already released modules

.github/workflows/add_reason_labels.yml, .github/workflows/update_dependencies.yml
=> Fix Syntax Error in Dependency Graph Update Workflow

.github/workflows/update_dependencies.yml
=> Fix incorrect if condition in sending PR

.github/workflows/update_dependencies.yml
=> Fix dependency update workflow not merging PRs

.github/workflows/update_dependencies.yml
=> Ignore changes in Dependencies.toml

.gitignore
=> Ignore Dependencies.toml in commits

.github/workflows/test_stdlib_releases_with_staging.yml
$subject 
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2933
=> Add workflow to automate integration tests with staging

.github/workflows/test_stdlib_releases_with_staging.yml
=> Make workflows run on specific version

.github/workflows/update_dependencies.yml
=> Fix workflow not coninuing issue

release/resources/stdlib_modules.json
=> Exclude releasing already released modules for 2201.2.0

.github/ISSUE_TEMPLATE/type_proposal.md
=> Update the proposal issue template to remove unncessary words

README.md
=> Change Slack reference to Discord

docs/build-and-release-guide.md
=> Add changes to address essential changes

.github/workflows/build-with-bal-test-native-template..yml, dashboard/constants.bal, dashboard/utils.bal
> $ Subject
> Related to : [`Incorporate GraalVM native-image test build to Std Libs daily build`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3316)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
=> Add `Build with bal test native` template and badge

.github/workflows/pull-request-build-template.yml
=> Fix syntax error in workflow template

.github/workflows/pull-request-build-template.yml, .github/workflows/release-package-template.yml
=> Add default values for inputs

.github/workflows/build-with-bal-test-native-template.yml
=> Adding required configs for standard libs windows build

release/resources/stdlib_modules.json
=> Disable already released package releases

docs/build-and-release-guide.md
=> Fix formatting

.github/workflows/trigger-load-tests-template.yml
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3750
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4072
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
=> Add load test trigger workflow template

.github/workflows/process-load-test-results-template.yml
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4072
> Link to the PR for changes to …
=> Add process load test results template

.github/workflows/trigger-load-tests-template.yml
=> Clean cluster name before invoking the load test

.github/workflows/process-load-test-results-template.yml
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4257
To be able to write load test results to any branch
=> Update process load test workflow to write results to any branch

.github/workflows/process-load-test-results-template.yml
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4257
=> Add support for processing results of any branch in load test results

dashboard/graph.bal, release/resources/module_list.json, release/resources/stdlib_modules.json
The current stdlib modules JSON file is hard to read. This PR will prettify the JSON content before writing to a file so that the files can be readable.
Used a third-party library to prettify the JSON. IMHO it would be okay to use that until we have something similar in Ballerina langlib or stdlib.
=> Update the dashboard generation script to prettify JSON files

docs/build-and-release-guide.md
=> Fix std lib modules list link in the doc

.github/workflows/build-with-bal-test-native-template.yml
> $Subject
> Related to : [`Add GraalVM check for the pull requests #4142`](https://github.com/ballerina-platform/ballerina-standard-library/issues/4142)
=> Add support to run GraalVM Check on pull request event trigger

.github/workflows/process-load-test-results-template.yml
=> Skip GraalVM Check for load-test automatic PR

.github/workflows/build-with-bal-test-native-template.yml
=> Increase pagefile size for windows GraalVM build

docs/adding-a-new-ballerina-module.md
=> Add the guide on creating a new Ballerina module

docs/adding-a-new-ballerina-module.md
=> Fix minor issues in module contribution guide

docs/adding-a-new-ballerina-module.md
=> Update the module creation guide

release/resources/module_list.json
> Related to:
https://github.com/ballerina-platform/ballerina-standard-library/issues/4394
https://github.com/ballerina-platform/ballerina-standard-library/issues/4395
=> Add yaml and toml modules to stdlib pipeline

release/resources/stdlib_modules.json
=> Skip Modules for Update 6

release/resources/module_list.json
=> Add ballerinax persist modules to standard library dashboard

.github/workflows/build-with-bal-test-graalvm-template.yml
> $Subject
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
=> Update graalvm test command

dashboard/constants.bal, docs/adding-a-new-ballerina-module.md
=> Update GraalVM Check workflow name

release/resources/module_list.json, release/resources/stdlib_modules.json
=> Update version key of the persist modules

docs/adding-a-new-ballerina-module.md, docs/build-and-release-guide.md
=> Update the build and release guide

.github/workflows/process-load-test-results-template.yml
When there are codecov issues, this workflow waits 6hrs before it automatically gets stopped. This is to reduce the timeout time. …
=> Add timeout for load-test workflows

.github/workflows/trigger-graalvm-check.yml, resources/workflow-scripts/trigger-graalvm-check.bal
This workflow will trigger `GraalVM Check` workflows in all the standard library modules listed in the [`./release/resources/stdlib_moduls.json`](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/release/resources/stdlib_modules.json).
The workflows will be triggered for the `default_branch` configured in the `stdlib_modules.json`. If we want to run the workflow in a different branch we can modify the `stdlib_modules.json` in a separate branch of `ballerina-standard-library`.
The following common inputs can be used to trigger the workflow:
- Ballerina lang branch or tag - default is `master`
- Ballerina version - optional when provided Ballerina lang build will be skipped
- Additional native image options - optional
This workflow will trigger the `GraalVM Check` …
=> Add GraalVM check trigger workflow for StdLib Modules

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Sync Java 17 changes with master

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Update workflow to use GraalVM for jdk-17.0.7

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Use traditional JDK for lang build

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Configure long path for Git in Windows

release/resources/module_list.json
> Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4714
=> Add soap module to stdlib pipeline

release/resources/module_list.json
=> Add `mqtt` module to standard library

release/resources/module_list.json
=> Add `java.jms` module to the standard library

.github/workflows/pull-request-build-template.yml
=> Update pull request build template workflow

.github/workflows/pull-request-build-template.yml
=> Fix placeholder issue in pull request build template

.github/workflows/release-package-template.yml
=> Update release-package-template workflow

.github/workflows/build-timestamp-master-template.yml, .github/workflows/central-publish-template.yml
=> Add central-publish-template and build-timestamp-master-template workflow

.github/workflows/trivy-scan-template.yml
=> Add trivy scan template workflow

.github/workflows/pull-request-build-template.yml
=> Update pull request template workflow to dynamically set env variables

.github/workflows/pr-build-connector-template.yml, .github/workflows/pull-request-build-connector-template.yml, .github/workflows/pull-request-build-template.yml
> Add a new workflow for connector PR build
> Remove the step of dynamically setting env from pull request workflow
> Link to the …
=> Add pr-build-connector-template

release/resources/module_list.json
=> Add math.vector package to Ballerina Library pipeline

.github/workflows/build-connector-template.yml, .github/workflows/daily-build-connector-template.yml
=> Add daily-build and build connector workflow templates

release/resources/module_list.json
=> Add version key to the math.vector package

.github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml
=> Add connector release workflow template and Update workflows to change base when sending PR

.github/workflows/central-publish-connector-template.yml, .github/workflows/dev-stage-central-publish-connector-template.yml, .github/workflows/release-package-connector-template.yml
- Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778 …
=> Add central publish connector template workflow and Add trivy scan step to release connector workflow

.github/workflows/build-with-bal-test-graalvm-template.yml
> Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778 …
=> Add step to dynamically set env variables in GraalVm template workflow

.github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/build-with-bal-test-graalvm-template.yml
- Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778 …
=> Add GraalVm check connector template workflow

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Add packageUser and packagePAT to GraalVm connector template workflow

.github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/dev-stage-central-publish-connector-template.yml
=> Fix inputs in connector workflows

.github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/dev-stage-central-publish-connector-template.yml
> Add ballerina setup step to GraalVM and dev/stage publish connector workflows
> Update set-java-home flag in GraalVM check connector workflow
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> Update GraalVM and dev/stage publish connector workflows

CONTRIBUTING.md
=> Fix the wording on library and package

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Update GraalVm connector template to use ballerina graalvm test command

.github/workflows/pull-request-build-template.yml
=> Skip JAVA_TOOL_OPTIONS for log module

docs/module-owners.md
=> Update module-owners for toml and yaml modules

docs/module-owners.md
=> Update module owners for task, cache, file, log and xmldata modules

.github/workflows/pull-request-build-template.yml
This reverts commit d8635f70538342a893c0edebb67b5fcbc56e8786.
> Link(s) to product documentation that addresses the changes of …
=> Revert "Skip JAVA_TOOL_OPTIONS for log module"

docs/module-owners.md
=> Update module ownership for email/jwt/websuhb/websubhub/http modules

.github/workflows/process-load-test-results-template.yml
> Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/4778 …
=> Update workflow check name in process load test template workflow

docs/module-owners.md
=> Add lib3 team module owners

.github/workflows/pull-request-build-template.yml
> $Subject
Fixes: https://github.com/ballerina-platform/module-ballerina-udp/pull/929 …
=> Add codecov token to pull request template workflow

.github/workflows/build-timestamp-master-template.yml, .github/workflows/central-publish-template.yml, .github/workflows/pull-request-build-template.yml, .github/workflows/release-package-template.yml
> This PR adds a step which pass the secret as environment variable
> Link to the PR for changes to the training content in …
=> Add step to dynamically set env variables in template workflows

docs/module-owners.md
=> Module owners

docs/module-owners.md
=> Add Ballerina Tool Repos to Module Owners Document

docs/module-owners.md
=> Add Module Owners List

docs/module-owners.md
=> Remove duplicated repo details

docs/module-owners.md, release/resources/module_list.json
$subject
Fixes https://github.com/ballerina-platform/ballerina-library/issues/5753
=> Add Gmail module to the dashboard

.github/workflows/dev-stage-central-publish-connector-template.yml
=> Fix dev/stage workflow

.github/workflows/dev-stage-central-publish-connector-template.yml
=> Set environment variables in dev/stage publishing

.github/workflows/dev-stage-central-publish-connector-template.yml
=> Fix indentation

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Add Directory Permissions to Delete Target Directory

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Use graalvm flag on Gradle

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Revert removing steps

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Remove Target Directory Before Bal Test

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> Remove balGraalVM flag

.github/workflows/trivy-scan-template.yml
=> Add additional-build-flags input to trivy scan template

docs/api-documentation-guide.md, docs/graalvm-compatibility-in-ballerina-libraries.md, docs/library-development-process.md, docs/load-test-guide.md, docs/zero-bug-policy.md
Fixing grammatical errors and typos in docs.
> Link to the PR for changes to the training content in …
=> docs: fix grammar issues and typos

.github/workflows/build-with-bal-test-graalvm-template.yml, .github/workflows/central-publish-template.yml, .github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml, .github/workflows/trivy-scan-template.yml
=> Remove skipping check task

.github/workflows/release-package-connector-template.yml
=> Remove build directory before release

.github/workflows/release-package-connector-template.yml
=> Create release branch before release

.github/workflows/release-package-connector-template.yml
=> Fix Release Workflow Failure

.github/workflows/release-package-connector-template.yml
=> Provide addtional release flags option

.github/workflows/release-package-connector-template.yml
=> Move `git-checkout` to a separate step

release/resources/module_list.json
=> Add persist tools to the dashboard

.github/workflows/daily-build-connector-template.yml
> Related to: https://github.com/ballerina-platform/ballerina-library/issues/5859
> Link to the PR for changes to the training …
=> Update daily build connector template to use nightly image

.github/workflows/pull-request-build-template.yml
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5999
Removed backslashes in the script to setting up environmental variables
=> Update PR Build workflow file to fix intermittent failures

docs/module-owners.md, release/resources/module_list.json
=> Add Redshift to Library Dashboard

dashboard/graph.bal, dashboard/tests/utils_test.bal
=> Fix code-cov N/A badge in dashboard

release/resources/module_list.json
=> Add Redis connector to the library dashboard

release/resources/module_list.json
=> Reorder Redis connector metadata according to alphabetical order

docs/adding-a-new-ballerina-module.md
=> Remove unwanted escape characters

.github/workflows/pull-request-build-template.yml
=> Enable central logs

.github/workflows/pull-request-build-template.yml
=> Remove central logs

release/resources/module_list.json
=> Add MongoDB to the Ballerina Library Dashboard

release/resources/module_list.json, release/resources/stdlib_modules.json
=> Add IBM MQ to the Ballerina Library Dashboard

release/resources/module_list.json
=> Add GitHub, Candid to Library Dashboard

release/resources/module_list.json
$subject to fix library dashboard rendering
> Link to the PR for changes to the training content in …
=> Fix extra space in candid module entry

release/resources/module_list.json
> $subject
Fixes https://github.com/ballerina-platform/ballerina-library/issues/6236
> Link to the PR for changes to the training …
=> Add ASB connector and EDI tools

release/resources/module_list.json
=> Add data.jsondata and data.xmldata packages to Ballerina Library pipeline

.github/workflows/release-package-connector-template.yml
=> Add directory path for the trivy scan in the connector release workflow

dashboard/constants.bal
=> Update the Build Workflow Name for the Dashboard Badge

release/resources/module_list.json
=> Add Google Calendar, DocuSign, Confluent, Avro modules to the library dashboard

release/resources/module_list.json
=> Fix Google calendar repo name in module list

docs/module-owners.md
=> Update the module owner for MongoDB

release/resources/module_list.json
=> Add dynamodb, dynamodb streams and sns modules to the libraries list

release/resources/module_list.json
=> Add snowflake to the module list

release/resources/module_list.json
=> Move persist.* libraries to modules section

resources/workflow-scripts/trigger-graalvm-check.bal
=> Fix the GraalVM run script with module.json file changes 

.github/workflows/process-load-test-results-template.yml
=> Temporarily remove codecov check from load test PR processing

.github/workflows/update_dependencies.yml
=> Commit Dependencies.toml file after dashboard generation is run

docs/build-and-release-guide.md
=> Fix build and release guide metadata

docs/module-owners.md, release/resources/module_list.json
=> Add salesforce modules to dashboard

.github/workflows/pr-build-connector-template.yml
With this change, the PR build for connectors will set up Ballerina with the version specified in the `gradle.properties` file. The default value is `latest`
=> Set Ballerina version from the properties

dashboard/constants.bal
=> Update the tools dashboard description

release/resources/module_list.json
=> Update `guidewire.insnow` connector category

release/resources/module_list.json
=> Update Asana, Candid and Zendesk connector entries in the dashboard

release/resources/module_list.json
=> Add sap module to the dashboard

docs/module-owners.md
=> Add code owner for sap module

docs/connector-development-process.md
=> Remove duplicate title of the connector development process

dashboard/github.bal
=> Fix release badge link

.github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-build-with-bal-test-graalvm.yml, .github/workflows/s4hana-daily-build-connector-template.yml, .github/workflows/s4hana-dev-stage-central-publish-template.yml, .github/workflows/s4hana-pr-template.yml, .github/workflows/s4hana-release-template.yml, .github/workflows/s4hana-trivy-scan.yml
=> Fix release template trivy scan configs

.github/workflows/apply-library-repo-templates.yml
=> Fix error in library template workflow

.github/workflows/apply-library-repo-templates.yml
=> Fix repo_name input handling in library template workflow

.github/workflows/apply-library-repo-templates.yml
=> Fix permission issue in apply-library-repo-templates.yml

release/resources/module_list.json
=> Add data.yaml module to module list

library-templates/generated-connector-template/files/docs/spec/sanitations.md, library-templates/generated-connector-template/files/examples/README.md, library-templates/generated-connector-template/files/examples/build.gradle, library-templates/generated-connector-template/files/examples/build.sh, library-templates/generated-connector-template/scripts/replace_placeholders.bal
$subject.
Related to https://github.com/ballerina-platform/ballerina-library/issues/6745 …
=> Add connector examples templates to the library workflow

release/resources/module_list.json
=> Add LDAP module to the module list

docs/build-and-release-guide.md
Updated the release guide with the information about updating the distribution when releasing a module
=> Update release guide

release/resources/module_list.json
=> Add Stripe connector to the library dashboard

library-templates/generated-connector-template/files/ballerina/Ballerina.toml, library-templates/generated-connector-template/files/build-config/resources/Ballerina.toml, library-templates/generated-connector-template/files/examples/README.md
=> Update the template for Ballerina connector modules

docs/build-and-release-guide.md
=> Fix ambiguous instructions in release process

release/resources/module_list.json
=> Update library dashboard with new connectors

release/resources/module_list.json
=> Add AWS marketplace connectors to the library dashboard

docs/adding-a-new-ballerina-module.md
=> Update guidelines to add new module to the library dashboard

.github/workflows/build-timestamp-master-template.yml, .github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-pr-template.yml
=> Update `upload-artifact` action version

.github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-pr-template.yml
=> Fix cov report upload

.github/CODEOWNERS
=> Update codeowner file

.github/workflows/build-connector-template.yml, .github/workflows/build-timestamp-master-template.yml, .github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/build-with-bal-test-graalvm-template.yml, .github/workflows/central-publish-template.yml, .github/workflows/daily-build-connector-template.yml, .github/workflows/dev-stage-central-publish-connector-template.yml, .github/workflows/pr-build-connector-template.yml, .github/workflows/pull-request-build-template.yml, .github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml, .github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-build-with-bal-test-graalvm.yml, .github/workflows/s4hana-daily-build-connector-template.yml, .github/workflows/s4hana-dev-stage-central-publish-template.yml, .github/workflows/s4hana-dev-stage-central-single-publish-template.yml, .github/workflows/s4hana-pr-template.yml, .github/workflows/s4hana-release-template.yml, .github/workflows/s4hana-trivy-scan.yml, .github/workflows/test_stdlib_releases_with_staging.yml, .github/workflows/trivy-scan-template.yml, docs/graalvm-compatibility-in-ballerina-libraries.md, library-templates/generated-connector-template/files/README.md, library-templates/generated-connector-template/files/ballerina/Ballerina.toml, library-templates/generated-connector-template/files/build-config/resources/Ballerina.toml
=> Migrate to Java 21

.github/workflows/build-with-bal-test-graalvm-template.yml, .github/workflows/pull-request-build-template.yml
> Related to: https://github.com/ballerina-platform/ballerina-library/issues/7030#issuecomment-2393177522
> Link to the PR for …
=> Update ubuntu image version to ubuntu-20.04 in pull request and graalvm test workflows 

.github/workflows/build-with-bal-test-graalvm-template.yml, .github/workflows/pull-request-build-template.yml
Reverts ballerina-platform/ballerina-library#7232
=> Revert "Update ubuntu image version to ubuntu-20.04 in pull request and graalvm test workflows "

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Update lang default branch

.github/workflows/central-publish-template.yml, .github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml, .github/workflows/s4hana-release-template.yml, .github/workflows/s4hana-trivy-scan.yml, .github/workflows/trivy-scan-template.yml
This is done as a workaround for https://github.com/aquasecurity/trivy-action/issues/404
> Link(s) to product documentation …
=> Downgrade trivy action version

.github/workflows/trivy-scan-template.yml
> $subject
**Note: This change is required for the latest Ballerina Gradle plugin based builds.**
=> Update trivy-scan to use the package specified Ballerina version

library-templates/generated-connector-template/scripts/replace_placeholders.bal
Fixes: https://github.com/ballerina-platform/ballerina-library/actions/runs/11339835248/job/31535260416
> Link to the PR for …
=> Skip processing jar file in replace_placeholder.bal file

.github/workflows/apply-library-repo-templates.yml
=> Fix template workflow to include hidden files

library-templates/generated-connector-template/files/ballerina/Ballerina.toml
=> Comment icon config in Ballerina.toml

.github/workflows/trivy-scan-template.yml
> Related to: https://github.com/aquasecurity/trivy-action/issues/404
> Link to the PR for changes to the training content in …
=> Update trivy scan template to use latest version

.github/workflows/trivy-scan-template.yml
=> Remove setup-ballerina action from the standard-library trivy-scan

.github/workflows/central-publish-template.yml, .github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml, .github/workflows/s4hana-release-template.yml, .github/workflows/s4hana-trivy-scan.yml, .github/workflows/trivy-scan-template.yml
> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7385
Sample trivy runs:
- [Without cache](https://github.com/ballerina-platform/module-ballerina-constraint/actions/runs/11927324554/job/33242527363#step:6:1)
- [With cache](https://github.com/ballerina-platform/module-ballerina-constraint/actions/runs/11927350367/job/33242586933#step:6:1)
=> Overwrite the trivy cache directory

release/resources/module_list.json
=> Add csv data module into standard library module list

docs/graalvm-compatibility-in-ballerina-libraries.md
=> Update GraalVM versions specific to Ballerina version

docs/build-and-release-guide.md
>  Update the guide with RM task.
> Maintaining a time log for each release can aid in understanding the release process. …
=> Update release guide with time log maintaining task

.github/workflows/trivy-scan-connector-template.yml
> $subject
Fixes: [#7352](https://github.com/ballerina-platform/ballerina-library/issues/7352)
=> Add new workflow for connector trivy-scan

.github/workflows/apply-library-repo-templates.yml, .github/workflows/build-connector-template.yml, .github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/daily-build-connector-template.yml, .github/workflows/dev-stage-central-publish-connector-template.yml, .github/workflows/pr-build-connector-template.yml, .github/workflows/release-package-connector-template.yml
> $subject
Part of: [#6838](https://github.com/ballerina-platform/ballerina-library/issues/6838)
=> Update setup-ballerina action version

.github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/daily-build-connector-template.yml
> $subject
Part of: [#6838](https://github.com/ballerina-platform/ballerina-library/issues/6838)
=> Add  `ignoreVersionMismatch` flag to the connector graalvm-build and daily-build

.github/workflows/build-with-bal-test-graalvm-connector-template.yml, .github/workflows/daily-build-connector-template.yml
> $subject
Related to: [#6838](https://github.com/ballerina-platform/ballerina-library/issues/6838)
=> Revert workflow changes done for gradle plugin update

.github/workflows/pr-build-connector-template.yml
=> Use `2201.11.0-pre-rc1` tag for PR connector build

.github/workflows/apply-library-repo-templates.yml
=> Fork the repo before cloning

.github/workflows/build-connector-template.yml, .github/workflows/pr-build-connector-template.yml
=> Pass docker tag directly to `gradlew` using `PbuildUsingDocker` CLI argument

.github/workflows/pr-build-connector-template.yml
=> Switch version to nightly

.github/workflows/pr-build-connector-template.yml
=> Update setup-ballerina version

.github/workflows/pr-build-connector-template.yml
=> Update setup-ballerina version and switch to nightly

.github/CODEOWNERS, release/resources/module_list.json
=> Add HubSpot connectors to the dashboard

.github/workflows/dev-stage-central-publish-connector-template.yml
=> Temporarily enable verbose logs for central client

release/resources/module_list.json
=> Update the version key of data modules

.github/workflows/release_pipeline.yml
=> Add missing workflow parameter

.github/workflows/build-connector-template.yml, .github/workflows/build-timestamp-master-template.yml, .github/workflows/pr-build-connector-template.yml, .github/workflows/pull-request-build-template.yml, .github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-pr-template.yml
=> [2201.10.x] Update Code Coverage Report Publication Workflows

.github/workflows/build-connector-template.yml, .github/workflows/pr-build-connector-template.yml
> Fixes https://github.com/ballerina-platform/ballerina-library/issues/7515
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Revert use of `nightly` in connector workflow and remove unnecessary flags

.github/workflows/build-with-bal-test-graalvm-connector-template.yml
=> [2201.10.x] Update ballerina version

.github/workflows/build-connector-template.yml, .github/workflows/build-timestamp-master-template.yml, .github/workflows/pr-build-connector-template.yml, .github/workflows/pull-request-build-template.yml, .github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-pr-template.yml
=> [2201.10.x] Fix Codecov slug path

release/resources/module_list.json
=> Add new Hubspot modules to the library dashboard

.github/workflows/regenerate-connector-template.yml, .github/workflows/regenerate-connectors.yml, regenerate-openapi-connectors/main.bal
=> Increase workflow start wait time and fix index out of range error

.github/workflows/regenerate-connector-template.yml
=> Fix working directory for reading file extension in regenerate-connectors workflow

.github/workflows/regenerate-connectors.yml, regenerate-openapi-connectors/main.bal
=> Fix the connector regeneration workflow

release/resources/module_list.json
=> Add the np module to the module list

release/resources/module_list.json
> Following tools will be added to the dashboard.
- Wsdl tool
- Xsd tool
- Consoldate packages tool
=> Include missing tools in the library dashboard

.github/workflows/pull-request-build-template.yml
=> Set config to ignore clrf endings for checkstyle check

.github/workflows/build-with-bal-test-graalvm-template.yml
=> Fix multi command execution

release/resources/module_list.json
=> Add cdc modules

release/resources/module_list.json
=> Fix repo name

library-templates/generated-connector-template/files/examples/build.bat, library-templates/generated-connector-template/files/examples/build.gradle, library-templates/generated-connector-template/files/examples/build.sh
=> Make examples build windows compatible

release/resources/module_list.json
=> Add sfmc connector to dashboard

.github/workflows/release-package-template.yml
- Enable central verbose for publish release workflow
=> Enable central verbose for publish release workflow

.github/workflows/build-with-bal-test-graalvm-template.yml
This change is reverted in other workflows, which is causing the test failures in Windows builds.
> Link(s) to product …
=> Revert the ignore clrf endings from workflow
