release/src/publish/publish.bal
Since now we are checking each of the module build statuses in order to proceed with the build process, there are two cases we have to consider:
1. The modules that have dependents.
2. Modules that don't have dependents.
When a module does not have any dependent, it's not necessary for that module to succeed to continue the process. This PR will consider that case, and when a module build is failed, if it does not have any dependents, the build process will continue.
=> Ignore build fails of non-dependee module build failures when publishing snapshots

release/src/publish/publish.bal
- Removed redundant logs
- Mark the publish workflow as failed, if one or more module build is failed
=> Remove redundant logs in publish workflow

release/src/module_dependencies/main.py
=> Sort module order ignoring the organization name

release/resources/module_list.json
Remove module-ballerina-ldap from pipeline with the Ballerina Authn/Authz desing for Swan Lake release [1].
[1] https://docs.google.com/document/d/1dGw5uUP6kqZNTwMfQ_Ik-k0HTMKhX70XpEA3tys9_kk/edit?usp=sharing
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/718
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Remove module-ballerina-ldap from pipeline

dependabot/update_repositories.py
With this update, Ballerina Stdlib Dependabot will only create a single PR for all the dependent modules in each Stdlib module repository.
=> Update stdlib dependabot to create single PR for all dependent modules

.github/workflows/update_dependencies.yml, release/src/version_update/main.py
Sync `automated-stdlib-version-update` branch with the default branch in Ballerina Distribution.
=> Add default branch sync before stdlib version update in Ballerina Distribution

dependabot/update_lang_version.py, dependabot/update_repositories.py, dependabot/update_version_data.py, release/src/version_update/main.py
With this PR, all the version updates will be coming from the same branch (`automated/version_update`). This will reduce the number of PRs sent after a release as well as reduce the complexity of merging PRs after a release since multiple PRs may resulted in conflicts, and also interdependency issues.
Additionally, when the lang version is updated, this will send a PR to the ballerina-distribution repo too.
=> Send all the version update PRs from the same branch

release/resources/stdlib_modules.json
The reason is it was released before.
=> Disable the time and java.arrays stdlib releases

release/resources/module_list.json, release/resources/stdlib_modules.json, release/src/module_dependencies/update_version_data.py
$subject since it is recommended to only use platform level URL to identify packages repositories. Because of this, we cannot identify dependencies based on the repository URL. 
The script is improved to parse the gradle.properties file to identify the version key of each modules' dependencies. 
Default version_key is stdlib + Capitalised artifact Name + Version
This can be overridden in the modules.json.
Improvement because of https://github.com/ballerina-platform/ballerina-release/issues/547
=> Improve dependency graph generator

resources/scripts/README.md, resources/scripts/build_standard_library.py
The standard library build script can now build up to the ballerina-distribution repo, and also can be used to execute any custom command inside each repo.
=> Add Flags to Build the Distribution and to use Custom Build Commands

SECURITY.md
This PR adds the "Security Policy" which explains how to report a security issue and refers to the detailed [Ballerina security policy](https://ballerina.io/security/). 
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
=> Add the security policy

release/src/module_dependencies/update_version_data.py
This PR adds the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner status of each standard library module to the dashboard.
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
=> Add Trivy scan status for dashboard

docs/api-documentation-guide.md
Review and improve the API Docs guidelines. 
Also, removed the duplicated API Docs guidelines from the `ballerina-distribution` repo and linked to this from it via https://github.com/ballerina-platform/ballerina-distribution/pull/2402 to avoid the duplication and ease the maintenance of the content.
=> Review and Improve the API Docs Guidelines

release/src/dependencies/utils.py, release/src/dependencies/utils_test.py
> $subject
This change is done to use the same load-test badge for WebSub and WebSubHub modules.
=> Update load-test badge generation script

.github/workflows/update_dependencies.yml, release/src/dependencies/requirements.txt, release/src/dependencies/utils.py
The update stdlib dependency graph workflow was failing due to a version mismatch of a python module (`networkx`). 
This PR will fix the versions of the python modules to a particular version (tested and passed), to avoid these kind of failures in the future.
=> Fix Dependency Update Workflow Failure

.github/ISSUE_TEMPLATE/type_bug.md, .github/ISSUE_TEMPLATE/type_improvement.md, .github/ISSUE_TEMPLATE/type_new_feature.md, .github/ISSUE_TEMPLATE/type_proposal.md, .github/ISSUE_TEMPLATE/type_task.md
This PR updates the GitHub issue templates for the updated version of the `type/*` labels.
=> Update issue templates for updated labels

.github/workflows/update_dependencies.yml, dashboard/constants.bal, dashboard/graph.bal, dashboard/remote.bal, dashboard/utils.bal
Currently, when the dashboard is changed, it is directly committed and pushed to the `main` branch. But the branch protection rules do not allow this. Therefore, with this PR, it is configured to send a PR, and approve using the ballerina reviewer bot and then merge it.
=> Update the Dashboard Generation to Send a PR

release/src/commons/functions.bal, release/src/commons/records.bal, release/src/release/release.bal
$subject
The release pipeline was failing due to a field key name mismatch in the [`stdlib_modules.json` ](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/release/resources/stdlib_modules.json)and the [`Module` record type](https://github.com/ballerina-platform/ballerina-standard-library/blob/a8faed4f5f5460872ee538413ee06376144f4e0c/release/src/commons/records.bal#L1-L11).
=> Fix issues in release script

.github/workflows/build-with-bal-test-native-template.yml
This env variable is set by default on windows runner since some of the standard libraries need this property to run the tests.
This PR will make setting `JAVA_TOOL_OPTIONS` env variable optional since having this as a default option for windows run is creating unexpected failures(See the issue below).
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3899
=> Make `java_tool_options` to be optional in GraalVM Check

resources/scripts/README.md, resources/scripts/build_standard_library.py
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4002
This will improve the Standard Library Build script with the following:
- There was a bug that prevented force-checkout the repositories. It is now fixed.
- When a full build is running, the SNAPSHOT build does not change the version number. It just replace the timestamp version with `SNAPSHOT`. This may cause issues when we build the full standard library using the script.
- Introduce `--from-module` flag: This will help to start the build from a particular module.
- Change the `--module` flag to `--up-to-module` to make the purpose of the flag clear.
- Change the warning color to Yellow from Red.
- Introduce `--continue-on-error` flag and make the default behavior to stop the subsequent builds when a …
=> Improve the Standard Library Full Build Script

.github/workflows/process-load-test-results-template.yml
Increase the label count obtained from `gh label list` command since the default limit is 30 and some of the standard libs has more than 50 labels.
=> Increase the label count limit when checking for `Skip GraalVM Check` label

.github/workflows/build-with-bal-test-graalvm-template.yml
> $Subject
Some repositories require other secrets as environment variables to run the build tasks. Since we are running the reusable workflow in the standard library repository we need to add them to the template file. The relevant module repositories will pass their secrets to the workflow using the `secrets: inherit` option.
=> Add additional secrets required to run GraalVM check

.github/workflows/build-connector-template.yml
=> Add publish-required flag to build-connector-template

dashboard/constants.bal, dashboard/remote.bal, dashboard/tests/utils_test.bal, dashboard/utils.bal, release/src/commons/functions.bal, resources/scripts/build_standard_library.py
Fixes
1. Bugs badge not shown properly due to repo name change
2. Fall back to ci.yml for connector builds
3. Use N/A badge for repos w/o Trivy scan
Note Had to disable several test cases as valid url check is failing in test environment
=> Fix dashboard failures

.github/workflows/release-package-connector-template.yml
The purpose of this PR is to address the issue raised in [Issue: Getting error `bal: command not found` on example build in connector release](https://github.com/ballerina-platform/ballerina-library/issues/5928). The problem arises from the absence of a Ballerina environment in the `release-package-connector-template`, leading to build failures when attempting to execute Ballerina commands.
The primary goal of this PR is to set up the Ballerina environment in the `release-package-connector-template`, ensuring that users can successfully build the example in the connector release without encountering the `bal: command not found` error.
To achieve this goal, the implementation involves configuring the necessary Ballerina binaries and dependencies in the `release-package-connector-template`. …
=> Add `set-up-ballerina` to connector release workflow

dashboard/Ballerina.toml, dashboard/graph.bal, dashboard/tests/utils_test.bal, dashboard/utils.bal, docs/module-owners.md, release/resources/module_list.json
=> Add Twilio to status dashboard

release/resources/module_list.json, release/resources/stdlib_modules.json
To list `persist.redis` as a Ballerina Extended module in Ballerina Library
=> Add Persist Redis module as a Ballerina Extended module

.github/workflows/build-with-bal-test-graalvm-template.yml, resources/workflow-scripts/trigger-graalvm-check.bal
The GraalVM windows builds in all the standard libraries are failing when building the lang master. This is due to the recent gradle task name change in the ballerina lang repo. (`createJavadoc` -> `javadoc`)
This PR is to address the above issue.
=> Fix Ballerina lang windows build failure in GraalVM check

.github/workflows/process-load-test-results-template.yml
The load-tests has been failing for some time due to the following issue:
- The merge PR step hangs intermittently and get timed-out, which makes the PR not merged until the next load test results PR
- Due to the above reason, there is already a `load-test-results` branch which is not sync with the master, which makes the push branch step fail
In this PR, the above issues has been addressed with the following changes:
- Use a github CLI command to wait until all the required checks pass
- Check for already existing branch and remove it before pushing the new changes - Ideally this check is not required when the PR is merged automatically
=> Fix process load test results workflow

.github/workflows/release-package-template.yml
With update 10, the `http` package has a dependency to `ballerinaToOpenApi` package which is in the `openapi-tool` repo. We need to release it first and should have the stable version in the `http` package. In this PR, the release workflow is updated with the change to support removing the timestamped version of `ballerinaToOpenApiVersion`.
=> Update release package workflow template

release/main.bal
The release workflow is failing with this error:
```
error: {ballerina}TypeCastError {"message":"incompatible types: 'string' cannot be cast to 'boolean'"}
```
It seems like the environment variables is read as string and we need to convert it to boolean rather than casting
=> Fix type cast error

.github/workflows/apply-library-repo-templates.yml, library-templates/generated-connector-template/files/README.md, library-templates/generated-connector-template/files/examples/README.md, library-templates/generated-connector-template/scripts/replace_placeholders.bal
This PR fixes a few minor issues identified in the connector template applying workflow and, also adds a few doc improvements
> …
=> Improve connector template workflow

.github/workflows/central-publish-template.yml, .github/workflows/release-package-connector-template.yml, .github/workflows/release-package-template.yml, .github/workflows/s4hana-release-template.yml, .github/workflows/s4hana-trivy-scan.yml, .github/workflows/trivy-scan-template.yml
> $Subject
Failure: https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays/actions/runs/11805232960/job/32887228609#step:6:157
The rate limiting is for the downloads from the GitHub container registry. As a solution, this PR adds the public ECR registry as a fallback option when the rate limit hits with the GitHub container registry.
Workflow run with this fix: https://github.com/ballerina-platform/module-ballerina-time/actions/runs/11810431587/job/32902393393#step:6:170
Reference: https://github.com/aquasecurity/trivy-action/issues/389
=> Fix `TOOMANYREQUESTS` failure in Trivy Action

release/Dependencies.toml, release/main.bal, release/types.bal
=> Fix release pipeline failure

.github/workflows/build-connector-template.yml, .github/workflows/build-timestamp-master-template.yml, .github/workflows/pr-build-connector-template.yml, .github/workflows/pull-request-build-template.yml, .github/workflows/s4hana-build-connector-template.yml, .github/workflows/s4hana-pr-template.yml
The current CodeCov slug path is invalid, leading to not publishing the codecov report. This will fix it.
=> Fix Codecov Slug Path

.github/workflows/regenerate-connector-template.yml, regenerate-openapi-connectors/main.bal
=> Add OpenAPI changes tool installation and generate change report in Regenerate OpenAPI Connectors Template workflow

.github/workflows/regenerate-connector-template.yml
=> Remove change report

.github/workflows/regenerate-connector-template.yml
=> Improve download step to get either json/yaml

regenerate-openapi-connectors/main.bal, regenerate-openapi-connectors/types.bal
=> Skip Multi-Module Repos in Connector Regeneration Workflow

.github/workflows/regenerate-connector-template.yml, regenerate-openapi-connectors/main.bal, regenerate-openapi-connectors/types.bal
=> Allow Connector Regeneration When Branch Exists

.github/workflows/regenerate-connector-template.yml
> $subject
Resolves [Connector Regeneration Workflow Should Only Check the PR Build Status ](https://github.com/ballerina-platform/ballerina-library/issues/7803)
=> Update auto PR merge step to only check for PR Build Status in Regenerate OpenAPI Connectors Workflow

.github/workflows/build-with-bal-test-graalvm-template.yml
Currently the GraalVM PR checks are always running against the lang master or the compatible patch version. This was initially added as to identify the GraalVM breaking changes with lang. But this introduces the following issues:
- Test time increase since we try to build the lang target branch
- We cannot test lang features(which included some GraalVM changes as well) by just updating the lang timestamp in the PR. This requires the PR to be merged to the lang master first which is not ideal
- GraalVM check failures in the PR can be misleading as the contributors are not aware of these internal details
- We already run daily GraalVM checks against the lang master, so having the same behaviour in the PR check is redundant
PR dispatch: …
=> Run the GraalVM PR checks with the existing lang version without building the lang master

.github/workflows/regenerate-connector-template.yml
There can be instances where the specification get changed(order of the schema fields) after flattening or aligning but there is no change in the generated code. We need to skip sending PR in such scenarios
=> Sent connector regeneration PR only when there is a change in regeneration

release/resources/module_list.json
> $Subject
Failure: https://github.com/ballerina-platform/ballerina-library/actions/runs/17602040361/job/50005849135#step:5:34
Due to the name change we are getting a redirect response. Since the Github client is not configured to follow redirects, currently it is failing with data-binding error.
=> Fix dashboard update failure due to repo name change
